Sprint 7 solution in file manager
PetrutikSA/java-kanban pull request #2
Opened 2024-04-08 15:18 UTC by PetrutikSA

Реализован FileBackedTaskManager способный к сохранению данных в файл и загрузки из него.
Файлы создает в корневой папке проекта. В тестах создает новые файлы перед каждым тестом, удаляет по окончанию каждого теста. Пользовательский сценарий, о котором говорится в доп задании не реализовывал,т.к. как покрыл как мне кажется в том числе указанные задания в тестах.

2024-04-09 12:57 UTC, afomkina requested changes

2024-04-09 12:57 UTC, afomkina commented on src/FileBackedTaskManager.java
> +public class FileBackedTaskManager extends InMemoryTaskManager implements TaskManager {
InMemoryTaskManager уже имплементирует интерфейс TaskManager

2024-04-09 12:57 UTC, afomkina commented on test/FileBackedTaskManagerTest.java
> +    Path testDB;
У полей не хватает модификаторов доступа

2024-04-09 12:57 UTC, afomkina commented on src/FileBackedTaskManager.java
Нужно распределить классы по пакетам, менеджеры вынести в отдельный пакет

2024-04-09 15:15 UTC, PetrutikSA commented
Исправил

2024-04-10 12:09 UTC, afomkina requested changes

2024-04-10 12:09 UTC, afomkina commented on test/FileBackedTaskManagerTest.java
> +    private static final String currentDir = System.getProperty("user.dir");
Константы должны именоваться в SNAKE_CASE

2024-04-10 12:09 UTC, afomkina commented on test/FileBackedTaskManagerTest.java
> +    private static Path testDB;
`static` у полей класса нужны только в случае, если мы хотим сделать значение константный (`static final`) или же нам нужен к ним доступ из статического контекста. В любом другом случае лучше избегать `static` у полей класса, так как такой код не соответствует парадигме ООП

2024-04-10 12:09 UTC, afomkina commented on test/InMemoryHistoryManagerTest.java
> +    private static TaskManager taskManager;
static лишний

2024-04-10 12:09 UTC, afomkina commented on test/InMemoryTaskManagerTest.java
> +    private static TaskManager taskManager;
static лишний

2024-04-10 12:09 UTC, afomkina commented on test/tasks/EpicTest.java
> +    private static Epic epic2;
static лишний

2024-04-10 12:09 UTC, afomkina commented on test/tasks/SubtaskTest.java
> +    private static Subtask subtask2;
static лишний

2024-04-10 12:44 UTC, PetrutikSA commented
Исправил

2024-04-10 15:14 UTC, afomkina approved these changes

2024-04-19 13:40 UTC, merged