Sprint 8 solution time and duration
PetrutikSA/java-kanban pull request #3
Opened 2024-04-21 15:01 UTC by PetrutikSA

По ТЗ не указано как поступать с задачани не прошедшими валидацию на пересечение по времени с другими задачами, поэтому добавил возвращаемое значение методов create и update (были void),  если пересекается задача, то не добавляется в базу и возвращает false, если успешно добалено/обновлено - true. 
По тестам - не выделял абстрактный класс с тестами, т.к. изначально делил тесты. FileBackedTaskManager унаследован от InMemoryTaskManagerTest, поэтому в FileBackedTaskManagerTest проверял только взаимодейстие в контексте сохранения/загрузки, а в InMemoryTaskManagerTest - весь функционал. 
Сделал основное заддание по ТЗ, доп задание не делал (не уложиться по времени).

2024-04-22 14:30 UTC, afomkina requested changes
1) Не хватает тестов из тз: 

```
Для расчёта статуса Epic. Граничные условия:
a. Все подзадачи со статусом NEW.
b. Все подзадачи со статусом DONE.
c. Подзадачи со статусами NEW и DONE.
d. Подзадачи со статусом IN_PROGRESS.
```
2) По тз для каждого из менеджероа должны проверяться вся базовая и дополнительная функциональность, для этого нужно все таки выделить абстрактный класс, который избавит код от множественного дублирования

Нужно стараться максимально избавляться от дублирования в тестах, одинаковые сообщения - вынести в константы, создание объетов в утильные классы или `@BeforeEach`, повторяющийся код в отедльные методы или опять же в `@BeforeEach` / `@AfterEach`. Также, если будет возможность советую попробовать подекомпозировать тесты и разбить из на логические составляющие. Это можно сделать с помощью [@Nested классов](https://www.petrikainulainen.net/programming/testing/junit-5-tutorial-writing-nested-tests/). Так код станет более читаемым и его будет проще поддерживать

2024-04-23 14:46 UTC, PetrutikSA commented
Исправил
По поводу Nested классов с наскока не разобрался, не стал реализовывать т.к. может привести к дополнительным ошибкам, а через 1,5 недели жесткий дедлайн, не хочется дополнительно себе урезать время для изучения теории и итогового задания. После жесткокого дедлайна будут каникулы в неделю, на них посмотрю, постараюсь разобраться.

2024-04-23 14:53 UTC, PetrutikSA commented
Да и сейчас удалил класс MemoryHistoryManagerTest.java. Все тесты, которые были в нем по сути тестировали взаимодействие TaskManager-а с менеджером истории, поэтому перенес их в абстрактный тестовый класс, чтобы они тестировались для обеих реализаций, в том числе для FileBackedTaskManager.

2024-04-24 13:04 UTC, afomkina approved these changes

2024-04-24 14:08 UTC, merged