Sprint 9 solution http api
PetrutikSA/java-kanban pull request #4
Opened 2024-04-29 22:34 UTC by PetrutikSA

Класс Main удалил, т.к. он создавался только для демонстрации, а точка входа в программу по ТЗ установлена в HttpTaskServer. Handler-ы по эпикам и подзадачам унаследовал от TaskHandler-а, т.к. реализация функциональности аналогична, для истории и приритеных задач создал отдельный абстрактный класс т.к. оба возвращают List<Task>, и больше функциональности не несут.
По тестам так же постарался реализовать все одинаковые тесты через абрстанктные тестовые классы.

2024-04-30 18:38 UTC, afomkina requested changes

2024-04-30 18:38 UTC, afomkina commented on src/handlers/adapters/DurationAdapter.java
> +        String s = (duration == null) ? null : String.valueOf(duration.toMinutes());
Все однобуквенные переменные нужно переименовать

2024-04-30 18:38 UTC, afomkina commented on src/handlers/adapters/LocalDateTimeAdapter.java
> +    private final DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm:ss.SSS");
Строку паттерна нужно вынести в публичную константу и переиспользовать и в других классах

2024-04-30 18:38 UTC, afomkina commented on src/handlers/BaseHttpHandler.java
> +    protected void sendResponse(HttpExchange h, String text, int responseCode, boolean isTextJson) throws IOException {
Однобуквенные переменные делают код менее читаемым

2024-04-30 18:38 UTC, afomkina commented on src/handlers/type_tokens/TaskListTypeToken.java
> +public class TaskListTypeToken extends TypeToken<List<Task>> {
Класс используется только для тестов, нужно перенести в папку с тестами

2024-04-30 18:38 UTC, afomkina commented on test/BaseHttpHandlerTest.java
> +    protected HttpResponse<String> sendRequest(String method, String requestString, String additionalPath) throws IOException, InterruptedException {
Нужно тестить реальный функциональ, а не писать отдельный реквест для тестов

2024-04-30 18:38 UTC, afomkina commented on test/BaseTaskHandlerTest.java
> +        HttpResponse<String> response = sendRequest("GET", "/" + objectsInDB.get(0).getId());
_Опционально_
Начиная с java 21 теперь можно использовать метод `.getFirst()` вместо `.get(0)`. Он выглядит более читаемо

2024-04-30 18:38 UTC, afomkina commented on test/BaseTaskHandlerTest.java
> +        assertEquals(200, response.statusCode(), code200);
Задание со `"*"`:
Можно создать отдельное перечисление для HTTP кодов и использовать его вместо "голых" цифр. 
Так код будет выглядеть более читаемо и понятней. 
Примеры можно посмотреть в главе [Конструкторы, поля и методы перечисления](https://metanit.com/java/tutorial/3.8.php#:~:text=%D0%9A%D0%BE%D0%BD%D1%81%D1%82%D1%80%D1%83%D0%BA%D1%82%D0%BE%D1%80%D1%8B%2C%20%D0%BF%D0%BE%D0%BB%D1%8F%20%D0%B8%20%D0%BC%D0%B5%D1%82%D0%BE%D0%B4%D1%8B%20%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%81%D0%BB%D0%B5%D0%BD%D0%B8%D1%8F)

2024-05-03 19:54 UTC, PetrutikSA commented
По поводу метода sendRequest в классе BaseHttpHandlerTest - метод выделил чтобы избежать дублирования одинакового кода во всех тестах, объединив его в один для удобства использования.
Сейчас разделил на 3 отдельных для Get, Post и Delete, раз прошлая версия с конструкцей switch была не читаемой.
SendGetRequest — используется 12 раз
SendPostRequest — используется 5 раз
SendDeleteRequest — используется 3 раза

Остальные замечания исправил

2024-05-04 16:23 UTC, afomkina approved these changes

2024-05-06 11:16 UTC, merged